# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('attachments', models.ImageField(blank=True, null=True, upload_to='attachments', verbose_name='Attachements')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'InActive'), (2, 'Trash')], default=0, verbose_name='Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enquiryform',
                'verbose_name_plural': 'Enquiryforms',
                'ordering': ['id'],
            },
        ),
    ]
